In [1]:
import numpy as np
import imageio
import matplotlib.pyplot as plt
imagelist=['amber1.png','amber2.png','amy1.png','amy2.png','andrew1.png','andrew2.png','andy1.png','andy2.png','erin1.png','erin2.png','gabe1.png','gabe2.png','hill2.png','hill4.png','jack1.png','jack2.png','zach1.png','zach2.png']


In [2]:
train_img=[]
for file in imagelist:
    first=np.array(imageio.imread('Train/'+file))
    m,n=first.shape
    first=np.reshape(first,(m*n,1))
    train_img.append(first)


img_train=np.matrix(np.array(train_img))
train_img=np.transpose(img_train)
print(m,n)
print(train_img)
m,n=train_img.shape
print("train_img.shape=",m,n)

150 125
[[ 28  22  13 ... 220 163 197]
 [ 38  20  20 ... 217 160 188]
 [ 38  26  27 ... 224 149 193]
 ...
 [ 14  15 174 ... 197 106  69]
 [  9  22 126 ... 237 123  72]
 [ 20  20 128 ... 252 123  75]]
train_img.shape= 18750 18


In [3]:
#Reshaping the image
train_img=[]
for file in imagelist:
    first=np.array(imageio.imread('Train/'+file))
    m,n=first.shape
    first=np.reshape(first,(m*n,1))
    train_img.append(first)

print(m,n)
img_train=np.matrix(np.array(train_img))
train_img=np.transpose(img_train)
print(train_img)
m,n=train_img.shape
print("train_img.shape=",m,n)

150 125
[[ 28  22  13 ... 220 163 197]
 [ 38  20  20 ... 217 160 188]
 [ 38  26  27 ... 224 149 193]
 ...
 [ 14  15 174 ... 197 106  69]
 [  9  22 126 ... 237 123  72]
 [ 20  20 128 ... 252 123  75]]
train_img.shape= 18750 18


In [4]:
#calculating average face vector
avgface=np.ones((m,1))
for i in range(0,m):
    avgface[i]=np.mean(train_img[i])
print("The average face vector is",avgface)

#subtracting average face vector from all faces
for i in range(0,n):
    img_train[i]=img_train[i]-np.transpose(avgface)
print("img_train.shape=",img_train.shape)

The average face vector is [[124.16666667]
 [129.11111111]
 [135.44444444]
 ...
 [ 81.66666667]
 [ 85.44444444]
 [ 90.05555556]]
img_train.shape= (18, 18750)


In [5]:
#calculating covariance matrix
covmat=(img_train*np.transpose(img_train))
print("The covariance matrix is :")
#print(covmat)

#calculating eigen values out of covariance matrix
eigen,u=np.linalg.eig(covmat)
a,s,v=np.linalg.svd(covmat)
print("U matrix is")
print(u)
print("eigen values are")
print(eigen)


#determining value of k i.e.(no. of principal components)
summation=np.sum(s)
print(summation)
for k in range(1,len(s)):
    sigma=0
    for i in range(0,k):
        sigma+=s[i]
    sigma=sigma/summation
    if(sigma>=0.95):
        print("selected value of k is",k)
        break

The covariance matrix is
U matrix is
[[-0.27328029 -0.19986906  0.05664229  0.01214961  0.11654215 -0.13742942
   0.06776537  0.15358528 -0.19306177  0.07574868 -0.36211299  0.4420153
  -0.36771578  0.00774803 -0.16994737 -0.15455595  0.34735941 -0.3783485 ]
 [-0.19617353 -0.10904088  0.25381021  0.09344454  0.21738228 -0.08852265
  -0.34608312  0.35290164 -0.00926217 -0.18297129  0.47061958  0.03693675
   0.05384741 -0.39880512  0.26027241 -0.10650103  0.26663327  0.09239138]
 [-0.24881555 -0.08291509 -0.33511187 -0.04496296  0.17750026 -0.24343454
   0.30587334 -0.10757747 -0.04830972 -0.09143777  0.01443588 -0.57713443
   0.04012444  0.12776929  0.2995832  -0.25787022  0.26948046 -0.17380183]
 [-0.32164069  0.2107735   0.25040022 -0.21139189 -0.09163781  0.4650923
   0.09456698 -0.15446729 -0.31935994 -0.08958134 -0.26605577  0.08404617
   0.02977901  0.01485261  0.39823181 -0.14999447  0.07914502  0.33301703]
 [-0.19191947  0.42221557 -0.0182635  -0.29844545 -0.04447562 -0.22197718

In [6]:
#selecting k eigen vectors from the set of 18 vectors
eigenvectors=np.empty((k,18))
for i in range(0,k):
    temp=np.empty((1,18))
    for j in range(0,18):
        temp[0,j]=u[i,j]
    eigenvectors[i]=temp

print("selected eigen vectors are",eigenvectors)

#mapping selected eigen vectors to original image size in training set
mappedeigenvectors=train_img*np.transpose(eigenvectors)
print(mappedeigenvectors.shape)

weightmatrix=np.transpose(mappedeigenvectors)*np.transpose(img_train)
print(weightmatrix.shape)

selected eigen vectors are [[-0.27328029 -0.19986906  0.05664229  0.01214961  0.11654215 -0.13742942
   0.06776537  0.15358528 -0.19306177  0.07574868 -0.36211299  0.4420153
  -0.36771578  0.00774803 -0.16994737 -0.15455595  0.34735941 -0.3783485 ]
 [-0.19617353 -0.10904088  0.25381021  0.09344454  0.21738228 -0.08852265
  -0.34608312  0.35290164 -0.00926217 -0.18297129  0.47061958  0.03693675
   0.05384741 -0.39880512  0.26027241 -0.10650103  0.26663327  0.09239138]
 [-0.24881555 -0.08291509 -0.33511187 -0.04496296  0.17750026 -0.24343454
   0.30587334 -0.10757747 -0.04830972 -0.09143777  0.01443588 -0.57713443
   0.04012444  0.12776929  0.2995832  -0.25787022  0.26948046 -0.17380183]
 [-0.32164069  0.2107735   0.25040022 -0.21139189 -0.09163781  0.4650923
   0.09456698 -0.15446729 -0.31935994 -0.08958134 -0.26605577  0.08404617
   0.02977901  0.01485261  0.39823181 -0.14999447  0.07914502  0.33301703]
 [-0.19191947  0.42221557 -0.0182635  -0.29844545 -0.04447562 -0.22197718
  -0.3213

In [7]:
#Testing unknown face
image=imageio.imread('Test/andrew3.png')
m,n=image.shape
image=np.reshape(image,(m*n,1))
normalisedface=image-avgface
print(normalisedface.shape)
#After Normalizing the face
testweight = np.transpose(mappedeigenvectors)*normalisedface
print(testweight.shape)
transposeweightmatrix=np.transpose(weightmatrix)
m,n=transposeweightmatrix.shape
print(m,n)
flag=0
store=[]
for i in range(0,m):
    difference=transposeweightmatrix[i]-np.transpose(testweight)
    totaldiff=np.sum(np.power(difference,2))
    totaldiff=np.sqrt(totaldiff)
    print(totaldiff)
    store.append(totaldiff)
a = min(store)
print()
print(a)

(18750, 1)
(14, 1)
1086036065.8606997
1178368483.9886494
1140323800.2705164
1157814067.883968
1288573233.451119
1283619306.4596963
1179485192.6233654
1174546349.4795482
1174405291.6956177
1200549239.9023569
1230915469.1330388
1207173874.8645113
1304603081.7287152
1326191618.3595006
1219304263.1390634
1225949350.1103466
1249477110.733903
1247558833.1608634

1086036065.8606997
